IMX500_MICROPY_MODULE_DIR := $(USERMOD_DIR)
IMX500_MCU_SDK_ROOT := $(abspath $(IMX500_MICROPY_MODULE_DIR)/../../../..)
IMX500_MICROPY_BUILD_MODE ?= full
IMX500_MICROPY_PLATFORM ?= nrf52840_dk

ifeq ($(IMX500_MICROPY_BUILD_MODE),minimal)
SRC_USERMOD_CXX += $(IMX500_MICROPY_MODULE_DIR)/modimx500_mcu_sdk_min.cpp
CFLAGS_USERMOD += -I$(IMX500_MICROPY_MODULE_DIR)
CFLAGS_USERMOD += -DMODULE_IMX500_MCU_SDK_ENABLED=1
else ifeq ($(IMX500_MICROPY_BUILD_MODE),full)
ifeq ($(IMX500_MICROPY_PLATFORM),nrf52840_dk)
IMX500_NRF52840_DK_EXAMPLE_DIR := $(IMX500_MCU_SDK_ROOT)/examples/platform/nordic/nrf52840_dk/micropython_imx500_metadata_parse

SRC_USERMOD_CXX += $(IMX500_MICROPY_MODULE_DIR)/modimx500_mcu_sdk.cpp
SRC_USERMOD_LIB_CXX += $(IMX500_MICROPY_MODULE_DIR)/sdk_arducam.cpp
SRC_USERMOD_LIB_C += $(IMX500_MICROPY_MODULE_DIR)/sdk_ai_driver.c
SRC_USERMOD_LIB_C += $(IMX500_MICROPY_MODULE_DIR)/platform_nrf52840_dk.c
SRC_USERMOD_LIB_C += $(IMX500_MICROPY_MODULE_DIR)/libc_shim.c

CFLAGS_USERMOD += -I$(IMX500_NRF52840_DK_EXAMPLE_DIR)
CFLAGS_USERMOD += -I$(IMX500_MICROPY_MODULE_DIR)
CFLAGS_USERMOD += -I$(IMX500_MICROPY_MODULE_DIR)/sdk_version
CFLAGS_USERMOD += -I$(IMX500_MCU_SDK_ROOT)
CFLAGS_USERMOD += -I$(IMX500_MCU_SDK_ROOT)/third_party/flatbuffers/include
CFLAGS_USERMOD += -DMODULE_IMX500_MCU_SDK_ENABLED=1
CFLAGS_USERMOD += -DIMX500_MCU_SDK_SENSOR_MIPI_COMMAND=SENSOR_MIPI_1024x600_2LANES
CFLAGS_USERMOD += -DIMX500_MCU_SDK_SENSOR_MIPI_WIDTH=1024
CFLAGS_USERMOD += -DIMX500_MCU_SDK_SENSOR_MIPI_HEIGHT=600

CXXFLAGS_USERMOD += -std=gnu++17
CXXFLAGS_USERMOD += -fno-exceptions
CXXFLAGS_USERMOD += -fno-rtti
CXXFLAGS_USERMOD += -Wno-error=double-promotion
LIBS_USERMOD += -lstdc++
else
$(error Unsupported IMX500_MICROPY_PLATFORM='$(IMX500_MICROPY_PLATFORM)' for Makefile builds)
endif
else
$(error Unsupported IMX500_MICROPY_BUILD_MODE='$(IMX500_MICROPY_BUILD_MODE)'; use full or minimal)
endif
