set(FIRMWARE_CPP_DIR ${CMAKE_CURRENT_LIST_DIR}/imx500_firmware_cpp)
set(FIRMWARE_CPP_OUTPUT_DIR ${FIRMWARE_CPP_DIR}/imx500_firmware)
file(GLOB IMX500_FIRMWARE_CPP_FILES ${FIRMWARE_CPP_OUTPUT_DIR}/*.cpp)