set(FIRMWARE_C_DIR ${CMAKE_CURRENT_LIST_DIR}/imx500_firmware_c)
set(FIRMWARE_C_OUTPUT_DIR ${FIRMWARE_C_DIR}/imx500_firmware)
file(GLOB IMX500_FIRMWARE_C_FILES ${FIRMWARE_C_OUTPUT_DIR}/*.c)

set(IMX500_FIRMWARE_C_INCLUDE_DIRS
    ${FIRMWARE_C_DIR}
    ${FIRMWARE_C_OUTPUT_DIR}
)
