# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBDimension(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBDimension()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBDimension(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FBDimension
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBDimension
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBDimension
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FBDimension
    def SerializationIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBDimension
    def Padding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def FBDimensionStart(builder):
    builder.StartObject(4)

def Start(builder):
    FBDimensionStart(builder)

def FBDimensionAddId(builder, id):
    builder.PrependUint8Slot(0, id, 0)

def AddId(builder, id):
    FBDimensionAddId(builder, id)

def FBDimensionAddSize(builder, size):
    builder.PrependUint16Slot(1, size, 0)

def AddSize(builder, size):
    FBDimensionAddSize(builder, size)

def FBDimensionAddSerializationIndex(builder, serializationIndex):
    builder.PrependUint8Slot(2, serializationIndex, 0)

def AddSerializationIndex(builder, serializationIndex):
    FBDimensionAddSerializationIndex(builder, serializationIndex)

def FBDimensionAddPadding(builder, padding):
    builder.PrependUint8Slot(3, padding, 0)

def AddPadding(builder, padding):
    FBDimensionAddPadding(builder, padding)

def FBDimensionEnd(builder):
    return builder.EndObject()

def End(builder):
    return FBDimensionEnd(builder)
