# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBInputTensor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBInputTensor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBInputTensor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FBInputTensor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBInputTensor
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBInputTensor
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBInputTensor
    def NumOfDimensions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBInputTensor
    def Dimensions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBDimension import FBDimension
            obj = FBDimension()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBInputTensor
    def DimensionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBInputTensor
    def DimensionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # FBInputTensor
    def Shift(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FBInputTensor
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FBInputTensor
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def FBInputTensorStart(builder):
    builder.StartObject(7)

def Start(builder):
    FBInputTensorStart(builder)

def FBInputTensorAddId(builder, id):
    builder.PrependUint8Slot(0, id, 0)

def AddId(builder, id):
    FBInputTensorAddId(builder, id)

def FBInputTensorAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    FBInputTensorAddName(builder, name)

def FBInputTensorAddNumOfDimensions(builder, numOfDimensions):
    builder.PrependUint8Slot(2, numOfDimensions, 0)

def AddNumOfDimensions(builder, numOfDimensions):
    FBInputTensorAddNumOfDimensions(builder, numOfDimensions)

def FBInputTensorAddDimensions(builder, dimensions):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(dimensions), 0)

def AddDimensions(builder, dimensions):
    FBInputTensorAddDimensions(builder, dimensions)

def FBInputTensorStartDimensionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDimensionsVector(builder, numElems):
    return FBInputTensorStartDimensionsVector(builder, numElems)

def FBInputTensorAddShift(builder, shift):
    builder.PrependUint16Slot(4, shift, 0)

def AddShift(builder, shift):
    FBInputTensorAddShift(builder, shift)

def FBInputTensorAddScale(builder, scale):
    builder.PrependFloat32Slot(5, scale, 0.0)

def AddScale(builder, scale):
    FBInputTensorAddScale(builder, scale)

def FBInputTensorAddFormat(builder, format):
    builder.PrependUint8Slot(6, format, 0)

def AddFormat(builder, format):
    FBInputTensorAddFormat(builder, format)

def FBInputTensorEnd(builder):
    return builder.EndObject()

def End(builder):
    return FBInputTensorEnd(builder)
