# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBNetwork(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBNetwork()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBNetwork(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FBNetwork
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBNetwork
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FBNetwork
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBNetwork
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBNetwork
    def InputTensors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBInputTensor import FBInputTensor
            obj = FBInputTensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBNetwork
    def InputTensorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBNetwork
    def InputTensorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # FBNetwork
    def OutputTensors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBOutputTensor import FBOutputTensor
            obj = FBOutputTensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBNetwork
    def OutputTensorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBNetwork
    def OutputTensorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def FBNetworkStart(builder):
    builder.StartObject(5)

def Start(builder):
    FBNetworkStart(builder)

def FBNetworkAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    FBNetworkAddId(builder, id)

def FBNetworkAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    FBNetworkAddName(builder, name)

def FBNetworkAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    FBNetworkAddType(builder, type)

def FBNetworkAddInputTensors(builder, inputTensors):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(inputTensors), 0)

def AddInputTensors(builder, inputTensors):
    FBNetworkAddInputTensors(builder, inputTensors)

def FBNetworkStartInputTensorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputTensorsVector(builder, numElems):
    return FBNetworkStartInputTensorsVector(builder, numElems)

def FBNetworkAddOutputTensors(builder, outputTensors):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(outputTensors), 0)

def AddOutputTensors(builder, outputTensors):
    FBNetworkAddOutputTensors(builder, outputTensors)

def FBNetworkStartOutputTensorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputTensorsVector(builder, numElems):
    return FBNetworkStartOutputTensorsVector(builder, numElems)

def FBNetworkEnd(builder):
    return builder.EndObject()

def End(builder):
    return FBNetworkEnd(builder)
