# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBOutputTensor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBOutputTensor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBOutputTensor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FBOutputTensor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBOutputTensor
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBOutputTensor
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBOutputTensor
    def NumOfDimensions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBOutputTensor
    def Dimensions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBDimension import FBDimension
            obj = FBDimension()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBOutputTensor
    def DimensionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBOutputTensor
    def DimensionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # FBOutputTensor
    def BitsPerElement(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBOutputTensor
    def Shift(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FBOutputTensor
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FBOutputTensor
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def FBOutputTensorStart(builder):
    builder.StartObject(8)

def Start(builder):
    FBOutputTensorStart(builder)

def FBOutputTensorAddId(builder, id):
    builder.PrependUint8Slot(0, id, 0)

def AddId(builder, id):
    FBOutputTensorAddId(builder, id)

def FBOutputTensorAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    FBOutputTensorAddName(builder, name)

def FBOutputTensorAddNumOfDimensions(builder, numOfDimensions):
    builder.PrependUint8Slot(2, numOfDimensions, 0)

def AddNumOfDimensions(builder, numOfDimensions):
    FBOutputTensorAddNumOfDimensions(builder, numOfDimensions)

def FBOutputTensorAddDimensions(builder, dimensions):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(dimensions), 0)

def AddDimensions(builder, dimensions):
    FBOutputTensorAddDimensions(builder, dimensions)

def FBOutputTensorStartDimensionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDimensionsVector(builder, numElems):
    return FBOutputTensorStartDimensionsVector(builder, numElems)

def FBOutputTensorAddBitsPerElement(builder, bitsPerElement):
    builder.PrependUint8Slot(4, bitsPerElement, 0)

def AddBitsPerElement(builder, bitsPerElement):
    FBOutputTensorAddBitsPerElement(builder, bitsPerElement)

def FBOutputTensorAddShift(builder, shift):
    builder.PrependUint16Slot(5, shift, 0)

def AddShift(builder, shift):
    FBOutputTensorAddShift(builder, shift)

def FBOutputTensorAddScale(builder, scale):
    builder.PrependFloat32Slot(6, scale, 0.0)

def AddScale(builder, scale):
    FBOutputTensorAddScale(builder, scale)

def FBOutputTensorAddFormat(builder, format):
    builder.PrependUint8Slot(7, format, 0)

def AddFormat(builder, format):
    FBOutputTensorAddFormat(builder, format)

def FBOutputTensorEnd(builder):
    return builder.EndObject()

def End(builder):
    return FBOutputTensorEnd(builder)
