#ifndef APPARAMS_VERIFIER_H
#define APPARAMS_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef APPARAMS_READER_H
#include "apParams_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int apParams_fb_FBDimension_verify_table(flatcc_table_verifier_descriptor_t *td);
static int apParams_fb_FBInputTensor_verify_table(flatcc_table_verifier_descriptor_t *td);
static int apParams_fb_FBOutputTensor_verify_table(flatcc_table_verifier_descriptor_t *td);
static int apParams_fb_FBNetwork_verify_table(flatcc_table_verifier_descriptor_t *td);
static int apParams_fb_FBApParams_verify_table(flatcc_table_verifier_descriptor_t *td);

static int apParams_fb_FBDimension_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* id */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* size */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* serializationIndex */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* padding */)) return ret;
    return flatcc_verify_ok;
}

static inline int apParams_fb_FBDimension_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBDimension_identifier, &apParams_fb_FBDimension_verify_table);
}

static inline int apParams_fb_FBDimension_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBDimension_identifier, &apParams_fb_FBDimension_verify_table);
}

static inline int apParams_fb_FBDimension_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBDimension_type_identifier, &apParams_fb_FBDimension_verify_table);
}

static inline int apParams_fb_FBDimension_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBDimension_type_identifier, &apParams_fb_FBDimension_verify_table);
}

static inline int apParams_fb_FBDimension_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &apParams_fb_FBDimension_verify_table);
}

static inline int apParams_fb_FBDimension_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &apParams_fb_FBDimension_verify_table);
}

static inline int apParams_fb_FBDimension_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &apParams_fb_FBDimension_verify_table);
}

static inline int apParams_fb_FBDimension_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &apParams_fb_FBDimension_verify_table);
}

static int apParams_fb_FBInputTensor_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* numOfDimensions */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &apParams_fb_FBDimension_verify_table) /* dimensions */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* shift */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 4, 4) /* scale */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 1, 1) /* format */)) return ret;
    return flatcc_verify_ok;
}

static inline int apParams_fb_FBInputTensor_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBInputTensor_identifier, &apParams_fb_FBInputTensor_verify_table);
}

static inline int apParams_fb_FBInputTensor_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBInputTensor_identifier, &apParams_fb_FBInputTensor_verify_table);
}

static inline int apParams_fb_FBInputTensor_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBInputTensor_type_identifier, &apParams_fb_FBInputTensor_verify_table);
}

static inline int apParams_fb_FBInputTensor_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBInputTensor_type_identifier, &apParams_fb_FBInputTensor_verify_table);
}

static inline int apParams_fb_FBInputTensor_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &apParams_fb_FBInputTensor_verify_table);
}

static inline int apParams_fb_FBInputTensor_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &apParams_fb_FBInputTensor_verify_table);
}

static inline int apParams_fb_FBInputTensor_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &apParams_fb_FBInputTensor_verify_table);
}

static inline int apParams_fb_FBInputTensor_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &apParams_fb_FBInputTensor_verify_table);
}

static int apParams_fb_FBOutputTensor_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* numOfDimensions */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &apParams_fb_FBDimension_verify_table) /* dimensions */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* bitsPerElement */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 2, 2) /* shift */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 4, 4) /* scale */)) return ret;
    if ((ret = flatcc_verify_field(td, 7, 1, 1) /* format */)) return ret;
    return flatcc_verify_ok;
}

static inline int apParams_fb_FBOutputTensor_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBOutputTensor_identifier, &apParams_fb_FBOutputTensor_verify_table);
}

static inline int apParams_fb_FBOutputTensor_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBOutputTensor_identifier, &apParams_fb_FBOutputTensor_verify_table);
}

static inline int apParams_fb_FBOutputTensor_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBOutputTensor_type_identifier, &apParams_fb_FBOutputTensor_verify_table);
}

static inline int apParams_fb_FBOutputTensor_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBOutputTensor_type_identifier, &apParams_fb_FBOutputTensor_verify_table);
}

static inline int apParams_fb_FBOutputTensor_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &apParams_fb_FBOutputTensor_verify_table);
}

static inline int apParams_fb_FBOutputTensor_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &apParams_fb_FBOutputTensor_verify_table);
}

static inline int apParams_fb_FBOutputTensor_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &apParams_fb_FBOutputTensor_verify_table);
}

static inline int apParams_fb_FBOutputTensor_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &apParams_fb_FBOutputTensor_verify_table);
}

static int apParams_fb_FBNetwork_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* type */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &apParams_fb_FBInputTensor_verify_table) /* inputTensors */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 4, 0, &apParams_fb_FBOutputTensor_verify_table) /* outputTensors */)) return ret;
    return flatcc_verify_ok;
}

static inline int apParams_fb_FBNetwork_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBNetwork_identifier, &apParams_fb_FBNetwork_verify_table);
}

static inline int apParams_fb_FBNetwork_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBNetwork_identifier, &apParams_fb_FBNetwork_verify_table);
}

static inline int apParams_fb_FBNetwork_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBNetwork_type_identifier, &apParams_fb_FBNetwork_verify_table);
}

static inline int apParams_fb_FBNetwork_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBNetwork_type_identifier, &apParams_fb_FBNetwork_verify_table);
}

static inline int apParams_fb_FBNetwork_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &apParams_fb_FBNetwork_verify_table);
}

static inline int apParams_fb_FBNetwork_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &apParams_fb_FBNetwork_verify_table);
}

static inline int apParams_fb_FBNetwork_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &apParams_fb_FBNetwork_verify_table);
}

static inline int apParams_fb_FBNetwork_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &apParams_fb_FBNetwork_verify_table);
}

static int apParams_fb_FBApParams_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &apParams_fb_FBNetwork_verify_table) /* networks */)) return ret;
    return flatcc_verify_ok;
}

static inline int apParams_fb_FBApParams_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBApParams_identifier, &apParams_fb_FBApParams_verify_table);
}

static inline int apParams_fb_FBApParams_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBApParams_identifier, &apParams_fb_FBApParams_verify_table);
}

static inline int apParams_fb_FBApParams_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, apParams_fb_FBApParams_type_identifier, &apParams_fb_FBApParams_verify_table);
}

static inline int apParams_fb_FBApParams_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, apParams_fb_FBApParams_type_identifier, &apParams_fb_FBApParams_verify_table);
}

static inline int apParams_fb_FBApParams_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &apParams_fb_FBApParams_verify_table);
}

static inline int apParams_fb_FBApParams_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &apParams_fb_FBApParams_verify_table);
}

static inline int apParams_fb_FBApParams_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &apParams_fb_FBApParams_verify_table);
}

static inline int apParams_fb_FBApParams_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &apParams_fb_FBApParams_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* APPARAMS_VERIFIER_H */
