#ifndef APPARAMS_READER_H
#define APPARAMS_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct apParams_fb_FBDimension_table *apParams_fb_FBDimension_table_t;
typedef struct apParams_fb_FBDimension_table *apParams_fb_FBDimension_mutable_table_t;
typedef const flatbuffers_uoffset_t *apParams_fb_FBDimension_vec_t;
typedef flatbuffers_uoffset_t *apParams_fb_FBDimension_mutable_vec_t;
typedef const struct apParams_fb_FBInputTensor_table *apParams_fb_FBInputTensor_table_t;
typedef struct apParams_fb_FBInputTensor_table *apParams_fb_FBInputTensor_mutable_table_t;
typedef const flatbuffers_uoffset_t *apParams_fb_FBInputTensor_vec_t;
typedef flatbuffers_uoffset_t *apParams_fb_FBInputTensor_mutable_vec_t;
typedef const struct apParams_fb_FBOutputTensor_table *apParams_fb_FBOutputTensor_table_t;
typedef struct apParams_fb_FBOutputTensor_table *apParams_fb_FBOutputTensor_mutable_table_t;
typedef const flatbuffers_uoffset_t *apParams_fb_FBOutputTensor_vec_t;
typedef flatbuffers_uoffset_t *apParams_fb_FBOutputTensor_mutable_vec_t;
typedef const struct apParams_fb_FBNetwork_table *apParams_fb_FBNetwork_table_t;
typedef struct apParams_fb_FBNetwork_table *apParams_fb_FBNetwork_mutable_table_t;
typedef const flatbuffers_uoffset_t *apParams_fb_FBNetwork_vec_t;
typedef flatbuffers_uoffset_t *apParams_fb_FBNetwork_mutable_vec_t;
typedef const struct apParams_fb_FBApParams_table *apParams_fb_FBApParams_table_t;
typedef struct apParams_fb_FBApParams_table *apParams_fb_FBApParams_mutable_table_t;
typedef const flatbuffers_uoffset_t *apParams_fb_FBApParams_vec_t;
typedef flatbuffers_uoffset_t *apParams_fb_FBApParams_mutable_vec_t;
#ifndef apParams_fb_FBDimension_file_identifier
#define apParams_fb_FBDimension_file_identifier 0
#endif
/* deprecated, use apParams_fb_FBDimension_file_identifier */
#ifndef apParams_fb_FBDimension_identifier
#define apParams_fb_FBDimension_identifier 0
#endif
#define apParams_fb_FBDimension_type_hash ((flatbuffers_thash_t)0x772b5b36)
#define apParams_fb_FBDimension_type_identifier "\x36\x5b\x2b\x77"
#ifndef apParams_fb_FBDimension_file_extension
#define apParams_fb_FBDimension_file_extension "bin"
#endif
#ifndef apParams_fb_FBInputTensor_file_identifier
#define apParams_fb_FBInputTensor_file_identifier 0
#endif
/* deprecated, use apParams_fb_FBInputTensor_file_identifier */
#ifndef apParams_fb_FBInputTensor_identifier
#define apParams_fb_FBInputTensor_identifier 0
#endif
#define apParams_fb_FBInputTensor_type_hash ((flatbuffers_thash_t)0x5c4a73c3)
#define apParams_fb_FBInputTensor_type_identifier "\xc3\x73\x4a\x5c"
#ifndef apParams_fb_FBInputTensor_file_extension
#define apParams_fb_FBInputTensor_file_extension "bin"
#endif
#ifndef apParams_fb_FBOutputTensor_file_identifier
#define apParams_fb_FBOutputTensor_file_identifier 0
#endif
/* deprecated, use apParams_fb_FBOutputTensor_file_identifier */
#ifndef apParams_fb_FBOutputTensor_identifier
#define apParams_fb_FBOutputTensor_identifier 0
#endif
#define apParams_fb_FBOutputTensor_type_hash ((flatbuffers_thash_t)0x51d3d106)
#define apParams_fb_FBOutputTensor_type_identifier "\x06\xd1\xd3\x51"
#ifndef apParams_fb_FBOutputTensor_file_extension
#define apParams_fb_FBOutputTensor_file_extension "bin"
#endif
#ifndef apParams_fb_FBNetwork_file_identifier
#define apParams_fb_FBNetwork_file_identifier 0
#endif
/* deprecated, use apParams_fb_FBNetwork_file_identifier */
#ifndef apParams_fb_FBNetwork_identifier
#define apParams_fb_FBNetwork_identifier 0
#endif
#define apParams_fb_FBNetwork_type_hash ((flatbuffers_thash_t)0x4debfcd4)
#define apParams_fb_FBNetwork_type_identifier "\xd4\xfc\xeb\x4d"
#ifndef apParams_fb_FBNetwork_file_extension
#define apParams_fb_FBNetwork_file_extension "bin"
#endif
#ifndef apParams_fb_FBApParams_file_identifier
#define apParams_fb_FBApParams_file_identifier 0
#endif
/* deprecated, use apParams_fb_FBApParams_file_identifier */
#ifndef apParams_fb_FBApParams_identifier
#define apParams_fb_FBApParams_identifier 0
#endif
#define apParams_fb_FBApParams_type_hash ((flatbuffers_thash_t)0xab3d1c0d)
#define apParams_fb_FBApParams_type_identifier "\x0d\x1c\x3d\xab"
#ifndef apParams_fb_FBApParams_file_extension
#define apParams_fb_FBApParams_file_extension "bin"
#endif



struct apParams_fb_FBDimension_table { uint8_t unused__; };

static inline size_t apParams_fb_FBDimension_vec_len(apParams_fb_FBDimension_vec_t vec)
__flatbuffers_vec_len(vec)
static inline apParams_fb_FBDimension_table_t apParams_fb_FBDimension_vec_at(apParams_fb_FBDimension_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(apParams_fb_FBDimension_table_t, vec, i, 0)
__flatbuffers_table_as_root(apParams_fb_FBDimension)

__flatbuffers_define_scalar_field(0, apParams_fb_FBDimension, id, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(1, apParams_fb_FBDimension, size, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, apParams_fb_FBDimension, serializationIndex, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(3, apParams_fb_FBDimension, padding, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct apParams_fb_FBInputTensor_table { uint8_t unused__; };

static inline size_t apParams_fb_FBInputTensor_vec_len(apParams_fb_FBInputTensor_vec_t vec)
__flatbuffers_vec_len(vec)
static inline apParams_fb_FBInputTensor_table_t apParams_fb_FBInputTensor_vec_at(apParams_fb_FBInputTensor_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(apParams_fb_FBInputTensor_table_t, vec, i, 0)
__flatbuffers_table_as_root(apParams_fb_FBInputTensor)

__flatbuffers_define_scalar_field(0, apParams_fb_FBInputTensor, id, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_string_field(1, apParams_fb_FBInputTensor, name, 0)
__flatbuffers_define_scalar_field(2, apParams_fb_FBInputTensor, numOfDimensions, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_vector_field(3, apParams_fb_FBInputTensor, dimensions, apParams_fb_FBDimension_vec_t, 0)
__flatbuffers_define_scalar_field(4, apParams_fb_FBInputTensor, shift, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(5, apParams_fb_FBInputTensor, scale, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(6, apParams_fb_FBInputTensor, format, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct apParams_fb_FBOutputTensor_table { uint8_t unused__; };

static inline size_t apParams_fb_FBOutputTensor_vec_len(apParams_fb_FBOutputTensor_vec_t vec)
__flatbuffers_vec_len(vec)
static inline apParams_fb_FBOutputTensor_table_t apParams_fb_FBOutputTensor_vec_at(apParams_fb_FBOutputTensor_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(apParams_fb_FBOutputTensor_table_t, vec, i, 0)
__flatbuffers_table_as_root(apParams_fb_FBOutputTensor)

__flatbuffers_define_scalar_field(0, apParams_fb_FBOutputTensor, id, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_string_field(1, apParams_fb_FBOutputTensor, name, 0)
__flatbuffers_define_scalar_field(2, apParams_fb_FBOutputTensor, numOfDimensions, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_vector_field(3, apParams_fb_FBOutputTensor, dimensions, apParams_fb_FBDimension_vec_t, 0)
__flatbuffers_define_scalar_field(4, apParams_fb_FBOutputTensor, bitsPerElement, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(5, apParams_fb_FBOutputTensor, shift, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(6, apParams_fb_FBOutputTensor, scale, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(7, apParams_fb_FBOutputTensor, format, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct apParams_fb_FBNetwork_table { uint8_t unused__; };

static inline size_t apParams_fb_FBNetwork_vec_len(apParams_fb_FBNetwork_vec_t vec)
__flatbuffers_vec_len(vec)
static inline apParams_fb_FBNetwork_table_t apParams_fb_FBNetwork_vec_at(apParams_fb_FBNetwork_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(apParams_fb_FBNetwork_table_t, vec, i, 0)
__flatbuffers_table_as_root(apParams_fb_FBNetwork)

__flatbuffers_define_scalar_field(0, apParams_fb_FBNetwork, id, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_string_field(1, apParams_fb_FBNetwork, name, 0)
__flatbuffers_define_string_field(2, apParams_fb_FBNetwork, type, 0)
__flatbuffers_define_vector_field(3, apParams_fb_FBNetwork, inputTensors, apParams_fb_FBInputTensor_vec_t, 0)
__flatbuffers_define_vector_field(4, apParams_fb_FBNetwork, outputTensors, apParams_fb_FBOutputTensor_vec_t, 0)

struct apParams_fb_FBApParams_table { uint8_t unused__; };

static inline size_t apParams_fb_FBApParams_vec_len(apParams_fb_FBApParams_vec_t vec)
__flatbuffers_vec_len(vec)
static inline apParams_fb_FBApParams_table_t apParams_fb_FBApParams_vec_at(apParams_fb_FBApParams_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(apParams_fb_FBApParams_table_t, vec, i, 0)
__flatbuffers_table_as_root(apParams_fb_FBApParams)

__flatbuffers_define_vector_field(0, apParams_fb_FBApParams, networks, apParams_fb_FBNetwork_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* APPARAMS_READER_H */
