#ifndef APPARAMS_BUILDER_H
#define APPARAMS_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef APPARAMS_READER_H
#include "apParams_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

static const flatbuffers_voffset_t __apParams_fb_FBDimension_required[] = { 0 };
typedef flatbuffers_ref_t apParams_fb_FBDimension_ref_t;
static apParams_fb_FBDimension_ref_t apParams_fb_FBDimension_clone(flatbuffers_builder_t *B, apParams_fb_FBDimension_table_t t);
__flatbuffers_build_table(flatbuffers_, apParams_fb_FBDimension, 4)

static const flatbuffers_voffset_t __apParams_fb_FBInputTensor_required[] = { 0 };
typedef flatbuffers_ref_t apParams_fb_FBInputTensor_ref_t;
static apParams_fb_FBInputTensor_ref_t apParams_fb_FBInputTensor_clone(flatbuffers_builder_t *B, apParams_fb_FBInputTensor_table_t t);
__flatbuffers_build_table(flatbuffers_, apParams_fb_FBInputTensor, 7)

static const flatbuffers_voffset_t __apParams_fb_FBOutputTensor_required[] = { 0 };
typedef flatbuffers_ref_t apParams_fb_FBOutputTensor_ref_t;
static apParams_fb_FBOutputTensor_ref_t apParams_fb_FBOutputTensor_clone(flatbuffers_builder_t *B, apParams_fb_FBOutputTensor_table_t t);
__flatbuffers_build_table(flatbuffers_, apParams_fb_FBOutputTensor, 8)

static const flatbuffers_voffset_t __apParams_fb_FBNetwork_required[] = { 0 };
typedef flatbuffers_ref_t apParams_fb_FBNetwork_ref_t;
static apParams_fb_FBNetwork_ref_t apParams_fb_FBNetwork_clone(flatbuffers_builder_t *B, apParams_fb_FBNetwork_table_t t);
__flatbuffers_build_table(flatbuffers_, apParams_fb_FBNetwork, 5)

static const flatbuffers_voffset_t __apParams_fb_FBApParams_required[] = { 0 };
typedef flatbuffers_ref_t apParams_fb_FBApParams_ref_t;
static apParams_fb_FBApParams_ref_t apParams_fb_FBApParams_clone(flatbuffers_builder_t *B, apParams_fb_FBApParams_table_t t);
__flatbuffers_build_table(flatbuffers_, apParams_fb_FBApParams, 1)

#define __apParams_fb_FBDimension_formal_args , uint8_t v0, uint16_t v1, uint8_t v2, uint8_t v3
#define __apParams_fb_FBDimension_call_args , v0, v1, v2, v3
static inline apParams_fb_FBDimension_ref_t apParams_fb_FBDimension_create(flatbuffers_builder_t *B __apParams_fb_FBDimension_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, apParams_fb_FBDimension, apParams_fb_FBDimension_file_identifier, apParams_fb_FBDimension_type_identifier)

#define __apParams_fb_FBInputTensor_formal_args ,\
  uint8_t v0, flatbuffers_string_ref_t v1, uint8_t v2, apParams_fb_FBDimension_vec_ref_t v3,\
  uint16_t v4, float v5, uint8_t v6
#define __apParams_fb_FBInputTensor_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6
static inline apParams_fb_FBInputTensor_ref_t apParams_fb_FBInputTensor_create(flatbuffers_builder_t *B __apParams_fb_FBInputTensor_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, apParams_fb_FBInputTensor, apParams_fb_FBInputTensor_file_identifier, apParams_fb_FBInputTensor_type_identifier)

#define __apParams_fb_FBOutputTensor_formal_args ,\
  uint8_t v0, flatbuffers_string_ref_t v1, uint8_t v2, apParams_fb_FBDimension_vec_ref_t v3,\
  uint8_t v4, uint16_t v5, float v6, uint8_t v7
#define __apParams_fb_FBOutputTensor_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7
static inline apParams_fb_FBOutputTensor_ref_t apParams_fb_FBOutputTensor_create(flatbuffers_builder_t *B __apParams_fb_FBOutputTensor_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, apParams_fb_FBOutputTensor, apParams_fb_FBOutputTensor_file_identifier, apParams_fb_FBOutputTensor_type_identifier)

#define __apParams_fb_FBNetwork_formal_args ,\
  uint16_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, apParams_fb_FBInputTensor_vec_ref_t v3, apParams_fb_FBOutputTensor_vec_ref_t v4
#define __apParams_fb_FBNetwork_call_args ,\
  v0, v1, v2, v3, v4
static inline apParams_fb_FBNetwork_ref_t apParams_fb_FBNetwork_create(flatbuffers_builder_t *B __apParams_fb_FBNetwork_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, apParams_fb_FBNetwork, apParams_fb_FBNetwork_file_identifier, apParams_fb_FBNetwork_type_identifier)

#define __apParams_fb_FBApParams_formal_args , apParams_fb_FBNetwork_vec_ref_t v0
#define __apParams_fb_FBApParams_call_args , v0
static inline apParams_fb_FBApParams_ref_t apParams_fb_FBApParams_create(flatbuffers_builder_t *B __apParams_fb_FBApParams_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, apParams_fb_FBApParams, apParams_fb_FBApParams_file_identifier, apParams_fb_FBApParams_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, apParams_fb_FBDimension_id, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBDimension)
__flatbuffers_build_scalar_field(1, flatbuffers_, apParams_fb_FBDimension_size, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), apParams_fb_FBDimension)
__flatbuffers_build_scalar_field(2, flatbuffers_, apParams_fb_FBDimension_serializationIndex, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBDimension)
__flatbuffers_build_scalar_field(3, flatbuffers_, apParams_fb_FBDimension_padding, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBDimension)

static inline apParams_fb_FBDimension_ref_t apParams_fb_FBDimension_create(flatbuffers_builder_t *B __apParams_fb_FBDimension_formal_args)
{
    if (apParams_fb_FBDimension_start(B)
        || apParams_fb_FBDimension_size_add(B, v1)
        || apParams_fb_FBDimension_id_add(B, v0)
        || apParams_fb_FBDimension_serializationIndex_add(B, v2)
        || apParams_fb_FBDimension_padding_add(B, v3)) {
        return 0;
    }
    return apParams_fb_FBDimension_end(B);
}

static apParams_fb_FBDimension_ref_t apParams_fb_FBDimension_clone(flatbuffers_builder_t *B, apParams_fb_FBDimension_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (apParams_fb_FBDimension_start(B)
        || apParams_fb_FBDimension_size_pick(B, t)
        || apParams_fb_FBDimension_id_pick(B, t)
        || apParams_fb_FBDimension_serializationIndex_pick(B, t)
        || apParams_fb_FBDimension_padding_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, apParams_fb_FBDimension_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, apParams_fb_FBInputTensor_id, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBInputTensor)
__flatbuffers_build_string_field(1, flatbuffers_, apParams_fb_FBInputTensor_name, apParams_fb_FBInputTensor)
__flatbuffers_build_scalar_field(2, flatbuffers_, apParams_fb_FBInputTensor_numOfDimensions, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBInputTensor)
__flatbuffers_build_table_vector_field(3, flatbuffers_, apParams_fb_FBInputTensor_dimensions, apParams_fb_FBDimension, apParams_fb_FBInputTensor)
__flatbuffers_build_scalar_field(4, flatbuffers_, apParams_fb_FBInputTensor_shift, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), apParams_fb_FBInputTensor)
__flatbuffers_build_scalar_field(5, flatbuffers_, apParams_fb_FBInputTensor_scale, flatbuffers_float, float, 4, 4, 0.00000000f, apParams_fb_FBInputTensor)
__flatbuffers_build_scalar_field(6, flatbuffers_, apParams_fb_FBInputTensor_format, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBInputTensor)

static inline apParams_fb_FBInputTensor_ref_t apParams_fb_FBInputTensor_create(flatbuffers_builder_t *B __apParams_fb_FBInputTensor_formal_args)
{
    if (apParams_fb_FBInputTensor_start(B)
        || apParams_fb_FBInputTensor_name_add(B, v1)
        || apParams_fb_FBInputTensor_dimensions_add(B, v3)
        || apParams_fb_FBInputTensor_scale_add(B, v5)
        || apParams_fb_FBInputTensor_shift_add(B, v4)
        || apParams_fb_FBInputTensor_id_add(B, v0)
        || apParams_fb_FBInputTensor_numOfDimensions_add(B, v2)
        || apParams_fb_FBInputTensor_format_add(B, v6)) {
        return 0;
    }
    return apParams_fb_FBInputTensor_end(B);
}

static apParams_fb_FBInputTensor_ref_t apParams_fb_FBInputTensor_clone(flatbuffers_builder_t *B, apParams_fb_FBInputTensor_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (apParams_fb_FBInputTensor_start(B)
        || apParams_fb_FBInputTensor_name_pick(B, t)
        || apParams_fb_FBInputTensor_dimensions_pick(B, t)
        || apParams_fb_FBInputTensor_scale_pick(B, t)
        || apParams_fb_FBInputTensor_shift_pick(B, t)
        || apParams_fb_FBInputTensor_id_pick(B, t)
        || apParams_fb_FBInputTensor_numOfDimensions_pick(B, t)
        || apParams_fb_FBInputTensor_format_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, apParams_fb_FBInputTensor_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, apParams_fb_FBOutputTensor_id, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBOutputTensor)
__flatbuffers_build_string_field(1, flatbuffers_, apParams_fb_FBOutputTensor_name, apParams_fb_FBOutputTensor)
__flatbuffers_build_scalar_field(2, flatbuffers_, apParams_fb_FBOutputTensor_numOfDimensions, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBOutputTensor)
__flatbuffers_build_table_vector_field(3, flatbuffers_, apParams_fb_FBOutputTensor_dimensions, apParams_fb_FBDimension, apParams_fb_FBOutputTensor)
__flatbuffers_build_scalar_field(4, flatbuffers_, apParams_fb_FBOutputTensor_bitsPerElement, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBOutputTensor)
__flatbuffers_build_scalar_field(5, flatbuffers_, apParams_fb_FBOutputTensor_shift, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), apParams_fb_FBOutputTensor)
__flatbuffers_build_scalar_field(6, flatbuffers_, apParams_fb_FBOutputTensor_scale, flatbuffers_float, float, 4, 4, 0.00000000f, apParams_fb_FBOutputTensor)
__flatbuffers_build_scalar_field(7, flatbuffers_, apParams_fb_FBOutputTensor_format, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), apParams_fb_FBOutputTensor)

static inline apParams_fb_FBOutputTensor_ref_t apParams_fb_FBOutputTensor_create(flatbuffers_builder_t *B __apParams_fb_FBOutputTensor_formal_args)
{
    if (apParams_fb_FBOutputTensor_start(B)
        || apParams_fb_FBOutputTensor_name_add(B, v1)
        || apParams_fb_FBOutputTensor_dimensions_add(B, v3)
        || apParams_fb_FBOutputTensor_scale_add(B, v6)
        || apParams_fb_FBOutputTensor_shift_add(B, v5)
        || apParams_fb_FBOutputTensor_id_add(B, v0)
        || apParams_fb_FBOutputTensor_numOfDimensions_add(B, v2)
        || apParams_fb_FBOutputTensor_bitsPerElement_add(B, v4)
        || apParams_fb_FBOutputTensor_format_add(B, v7)) {
        return 0;
    }
    return apParams_fb_FBOutputTensor_end(B);
}

static apParams_fb_FBOutputTensor_ref_t apParams_fb_FBOutputTensor_clone(flatbuffers_builder_t *B, apParams_fb_FBOutputTensor_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (apParams_fb_FBOutputTensor_start(B)
        || apParams_fb_FBOutputTensor_name_pick(B, t)
        || apParams_fb_FBOutputTensor_dimensions_pick(B, t)
        || apParams_fb_FBOutputTensor_scale_pick(B, t)
        || apParams_fb_FBOutputTensor_shift_pick(B, t)
        || apParams_fb_FBOutputTensor_id_pick(B, t)
        || apParams_fb_FBOutputTensor_numOfDimensions_pick(B, t)
        || apParams_fb_FBOutputTensor_bitsPerElement_pick(B, t)
        || apParams_fb_FBOutputTensor_format_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, apParams_fb_FBOutputTensor_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, apParams_fb_FBNetwork_id, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), apParams_fb_FBNetwork)
__flatbuffers_build_string_field(1, flatbuffers_, apParams_fb_FBNetwork_name, apParams_fb_FBNetwork)
__flatbuffers_build_string_field(2, flatbuffers_, apParams_fb_FBNetwork_type, apParams_fb_FBNetwork)
__flatbuffers_build_table_vector_field(3, flatbuffers_, apParams_fb_FBNetwork_inputTensors, apParams_fb_FBInputTensor, apParams_fb_FBNetwork)
__flatbuffers_build_table_vector_field(4, flatbuffers_, apParams_fb_FBNetwork_outputTensors, apParams_fb_FBOutputTensor, apParams_fb_FBNetwork)

static inline apParams_fb_FBNetwork_ref_t apParams_fb_FBNetwork_create(flatbuffers_builder_t *B __apParams_fb_FBNetwork_formal_args)
{
    if (apParams_fb_FBNetwork_start(B)
        || apParams_fb_FBNetwork_name_add(B, v1)
        || apParams_fb_FBNetwork_type_add(B, v2)
        || apParams_fb_FBNetwork_inputTensors_add(B, v3)
        || apParams_fb_FBNetwork_outputTensors_add(B, v4)
        || apParams_fb_FBNetwork_id_add(B, v0)) {
        return 0;
    }
    return apParams_fb_FBNetwork_end(B);
}

static apParams_fb_FBNetwork_ref_t apParams_fb_FBNetwork_clone(flatbuffers_builder_t *B, apParams_fb_FBNetwork_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (apParams_fb_FBNetwork_start(B)
        || apParams_fb_FBNetwork_name_pick(B, t)
        || apParams_fb_FBNetwork_type_pick(B, t)
        || apParams_fb_FBNetwork_inputTensors_pick(B, t)
        || apParams_fb_FBNetwork_outputTensors_pick(B, t)
        || apParams_fb_FBNetwork_id_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, apParams_fb_FBNetwork_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, apParams_fb_FBApParams_networks, apParams_fb_FBNetwork, apParams_fb_FBApParams)

static inline apParams_fb_FBApParams_ref_t apParams_fb_FBApParams_create(flatbuffers_builder_t *B __apParams_fb_FBApParams_formal_args)
{
    if (apParams_fb_FBApParams_start(B)
        || apParams_fb_FBApParams_networks_add(B, v0)) {
        return 0;
    }
    return apParams_fb_FBApParams_end(B);
}

static apParams_fb_FBApParams_ref_t apParams_fb_FBApParams_clone(flatbuffers_builder_t *B, apParams_fb_FBApParams_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (apParams_fb_FBApParams_start(B)
        || apParams_fb_FBApParams_networks_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, apParams_fb_FBApParams_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* APPARAMS_BUILDER_H */
