#pragma once

#define AI_CAMERA_MULTITASK_SPI_METADATA_MODE_JPEG_INPUT_OUTPUT 0
#define AI_CAMERA_MULTITASK_SPI_METADATA_MODE_OUTPUT_TENSOR_ONLY 1

/*
 * Select the SPI metadata payload used by this example.
 *
 * JPEG_INPUT_OUTPUT:
 *   SPI carries a JPEG input thumbnail plus output tensors. AI overlays are
 *   drawn on the thumbnail.
 *
 * OUTPUT_TENSOR_ONLY:
 *   SPI carries output tensors only. AI overlays are scaled onto the MIPI
 *   camera image shown on the LCD.
 */
#ifndef AI_CAMERA_MULTITASK_SPI_METADATA_MODE
#define AI_CAMERA_MULTITASK_SPI_METADATA_MODE AI_CAMERA_MULTITASK_SPI_METADATA_MODE_OUTPUT_TENSOR_ONLY
#endif

#if AI_CAMERA_MULTITASK_SPI_METADATA_MODE == AI_CAMERA_MULTITASK_SPI_METADATA_MODE_JPEG_INPUT_OUTPUT
#define AI_CAMERA_MULTITASK_ENABLE_SPI_JPEG_THUMBNAIL 1
#elif AI_CAMERA_MULTITASK_SPI_METADATA_MODE == AI_CAMERA_MULTITASK_SPI_METADATA_MODE_OUTPUT_TENSOR_ONLY
#define AI_CAMERA_MULTITASK_ENABLE_SPI_JPEG_THUMBNAIL 0
#else
#error "Unsupported AI_CAMERA_MULTITASK_SPI_METADATA_MODE"
#endif
