# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBApParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBApParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBApParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FBApParams
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBApParams
    def Networks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FBNetwork import FBNetwork
            obj = FBNetwork()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBApParams
    def NetworksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBApParams
    def NetworksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FBApParamsStart(builder):
    builder.StartObject(1)

def Start(builder):
    FBApParamsStart(builder)

def FBApParamsAddNetworks(builder, networks):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(networks), 0)

def AddNetworks(builder, networks):
    FBApParamsAddNetworks(builder, networks)

def FBApParamsStartNetworksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNetworksVector(builder, numElems):
    return FBApParamsStartNetworksVector(builder, numElems)

def FBApParamsEnd(builder):
    return builder.EndObject()

def End(builder):
    return FBApParamsEnd(builder)
