#pragma once

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

#define INTEGRATION_TEST_BOOT_MODE_DIRECT 0
#define INTEGRATION_TEST_BOOT_MODE_FLASH  1

#define INTEGRATION_TEST_SPI_METADATA_FORMAT_OUTPUT_TENSOR 0
#define INTEGRATION_TEST_SPI_METADATA_FORMAT_JPEG_INPUT_TENSOR_OUTPUT_TENSOR 1

#ifndef INTEGRATION_TEST_BOOT_MODE
#define INTEGRATION_TEST_BOOT_MODE INTEGRATION_TEST_BOOT_MODE_FLASH
#endif

#ifndef INTEGRATION_TEST_SPI_METADATA_FORMAT
#define INTEGRATION_TEST_SPI_METADATA_FORMAT INTEGRATION_TEST_SPI_METADATA_FORMAT_JPEG_INPUT_TENSOR_OUTPUT_TENSOR
#endif

esp_err_t imx500_sdk_integration_test_run(void);

#ifdef __cplusplus
}
#endif
